### ISSUE TITLE
Notification of License Change for QuoteBot v2

### ISSUE THREAD

**Issue by RalphORama** [FriendosClub/QuoteBot#13]
Hello,

This issue is a notification of my intent to change QuoteBot's license from MIT to AGPL when I release v2. If you would like your code removed due to the license change, please let me know and I will roll back your commits.

- [x] @DakotaWorzella

**Comment by DakotaWorzella** [comment]
You can keep the changes. I don't mind

**Comment by RalphORama** [comment]
Awesome, thanks! 👍
